# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/james/Documents/c++Programs/Language

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/james/Documents/c++Programs/Language

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/Documents/c++Programs/Language/CMakeFiles /home/james/Documents/c++Programs/Language/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/Documents/c++Programs/Language/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Jay_lang

# Build rule for target.
Jay_lang: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Jay_lang
.PHONY : Jay_lang

# fast build rule for target.
Jay_lang/fast:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/build
.PHONY : Jay_lang/fast

ast.o: ast.cpp.o

.PHONY : ast.o

# target to build an object file
ast.cpp.o:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/ast.cpp.o
.PHONY : ast.cpp.o

ast.i: ast.cpp.i

.PHONY : ast.i

# target to preprocess a source file
ast.cpp.i:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/ast.cpp.i
.PHONY : ast.cpp.i

ast.s: ast.cpp.s

.PHONY : ast.s

# target to generate assembly for a file
ast.cpp.s:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/ast.cpp.s
.PHONY : ast.cpp.s

converter.o: converter.cpp.o

.PHONY : converter.o

# target to build an object file
converter.cpp.o:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/converter.cpp.o
.PHONY : converter.cpp.o

converter.i: converter.cpp.i

.PHONY : converter.i

# target to preprocess a source file
converter.cpp.i:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/converter.cpp.i
.PHONY : converter.cpp.i

converter.s: converter.cpp.s

.PHONY : converter.s

# target to generate assembly for a file
converter.cpp.s:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/converter.cpp.s
.PHONY : converter.cpp.s

errorLog.o: errorLog.cpp.o

.PHONY : errorLog.o

# target to build an object file
errorLog.cpp.o:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/errorLog.cpp.o
.PHONY : errorLog.cpp.o

errorLog.i: errorLog.cpp.i

.PHONY : errorLog.i

# target to preprocess a source file
errorLog.cpp.i:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/errorLog.cpp.i
.PHONY : errorLog.cpp.i

errorLog.s: errorLog.cpp.s

.PHONY : errorLog.s

# target to generate assembly for a file
errorLog.cpp.s:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/errorLog.cpp.s
.PHONY : errorLog.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/main.cpp.s
.PHONY : main.cpp.s

parser.o: parser.cpp.o

.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i

.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s

.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/parser.cpp.s
.PHONY : parser.cpp.s

scanner.o: scanner.cpp.o

.PHONY : scanner.o

# target to build an object file
scanner.cpp.o:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/scanner.cpp.o
.PHONY : scanner.cpp.o

scanner.i: scanner.cpp.i

.PHONY : scanner.i

# target to preprocess a source file
scanner.cpp.i:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/scanner.cpp.i
.PHONY : scanner.cpp.i

scanner.s: scanner.cpp.s

.PHONY : scanner.s

# target to generate assembly for a file
scanner.cpp.s:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/scanner.cpp.s
.PHONY : scanner.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/utils.cpp.s
.PHONY : utils.cpp.s

vm.o: vm.cpp.o

.PHONY : vm.o

# target to build an object file
vm.cpp.o:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/vm.cpp.o
.PHONY : vm.cpp.o

vm.i: vm.cpp.i

.PHONY : vm.i

# target to preprocess a source file
vm.cpp.i:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/vm.cpp.i
.PHONY : vm.cpp.i

vm.s: vm.cpp.s

.PHONY : vm.s

# target to generate assembly for a file
vm.cpp.s:
	$(MAKE) -f CMakeFiles/Jay_lang.dir/build.make CMakeFiles/Jay_lang.dir/vm.cpp.s
.PHONY : vm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Jay_lang"
	@echo "... ast.o"
	@echo "... ast.i"
	@echo "... ast.s"
	@echo "... converter.o"
	@echo "... converter.i"
	@echo "... converter.s"
	@echo "... errorLog.o"
	@echo "... errorLog.i"
	@echo "... errorLog.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... scanner.o"
	@echo "... scanner.i"
	@echo "... scanner.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... vm.o"
	@echo "... vm.i"
	@echo "... vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

